name: topojson
description: A Dart port of topojson.
version: 0.1.0
homepage: https://github.com/espresso3389/topojson

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
