name: topojson
description: A Topojson parser.
version: 0.3.0
homepage: https://github.com/espresso3389/topojson

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:

dev_dependencies:
  http: ^0.13.4
  lints: ^2.0.0
  test: ^1.16.0
